[package]
name = "juggling-tracker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = "0.88.8" # or whatever version is the latest
anyhow = "1.0"
